import "./globals.css";
import localFont from "next/font/local";
import Providers from "./providers"; // Importar el Providers client

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Aquí SI podemos exportar metadata, pues es un Server Component
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    {/* Envuelves los children en tu Providers client */}
    <Providers>
    {children}
    </Providers>
    </body>
    </html>
  );
}
